### ISSUE TITLE
Generalize main analyzer with event type plugins

### ISSUE THREAD

**Issue by hansenjo** [JeffersonLab/analyzer#14]
Different event types (physics, scalers, slow control, etc.) need different processing chains. These chains should be made pluggable so users can easily extend or replace them. This also helps split the large main analyzer into smaller and hopefully more maintainable subclasses.

**Comment by rwmichaels** [comment]
I made a pull request with plug-ins for Hall A Scalers, and the EPICS events can also be a plug-in but there is a currently an EPICS handler which is a member of THaAnalyzer.  The latter makes sense because it allows to re-use the existing THaEpics and THaOutput::ProcEpics in such a way as to make the user interface identical to before, plus I think that both Hall A and C does EPICS insertions the same way.  In any case, if preferred, someone can now write an EPICS handler plug-in, imitating the Hall A scalers plug-in as an example.  Likewise, someone can write a hall C scaler plug-in.

**Comment by hansenjo** [comment]
I will merge this shortly. I'll collapse the history a bit and I see if
it compiles on all my test platforms.

Ole

**Comment by hansenjo** [comment]
Closed by commit d2a4007b279cc924c0fa8612587df5c690542c98
